// 游戏数据
const SCRIPTS = [
  {
    "id": 390001,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 0,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "2026年1月，飞机划破北欧阴沉的天空。我，艾玛·安德森，紧握手中的手机，屏幕上是特朗普总统的最新推特：“格陵兰必须属于美国！丹麦不配合？他们的军队只有两个狗拉雪橇！”我的心沉到了谷底。",
    "choices": null,
    "createdAt": "2026-01-21T18:05:29.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390001.png",
    "miniGameId": null,
    "nextNodeId": 390002
  },
  {
    "id": 390002,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 1,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "哥本哈根机场外，寒风凛冽。街头抗议人群已经聚集，高呼着“美国佬，滚回家！”的口号。这场突如其来的危机，比我想象的还要严重。",
    "choices": null,
    "createdAt": "2026-01-21T18:05:36.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390002.png",
    "miniGameId": null,
    "nextNodeId": 390003
  },
  {
    "id": 390003,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 2,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "外交部紧急会议，气氛凝重。我的导师拉斯部长和格陵兰代表尼娜都坐在那里，等待我的意见。",
    "choices": null,
    "createdAt": "2026-01-21T18:05:44.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390003.png",
    "miniGameId": null,
    "nextNodeId": 390004
  },
  {
    "id": 390004,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 3,
    "nodeType": "dialog",
    "speaker": "拉斯部长",
    "side": "left",
    "avatar": "lars",
    "text": "艾玛，你对当前局势有什么看法？我们现在需要一个清晰的策略。",
    "choices": null,
    "createdAt": "2026-01-21T18:05:51.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390004.png",
    "miniGameId": null,
    "nextNodeId": 390005
  },
  {
    "id": 390005,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 4,
    "nodeType": "dialog",
    "speaker": "尼娜",
    "side": "left",
    "avatar": "nina",
    "text": "不能再等了！美国总统的言行是对我们主权的公然侵犯！我们必须强硬反击！",
    "choices": null,
    "createdAt": "2026-01-21T18:05:58.000Z",
    "emotion": "angry",
    "backgroundImage": "assets/backgrounds/scene_390005.png",
    "miniGameId": null,
    "nextNodeId": 390006
  },
  {
    "id": 390006,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 5,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "（拉斯部长主张拖延，尼娜主张独立……而我，必须做出第一个选择，决定丹麦的下一步。）",
    "choices": null,
    "createdAt": "2026-01-21T18:06:05.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390006.png",
    "miniGameId": null,
    "nextNodeId": 390007
  },
  {
    "id": 390007,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 6,
    "nodeType": "choice",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "你决定采取什么立场？",
    "choices": [
      {
        "text": "强硬立场，直接拒绝美国的要求。",
        "targetNodeId": 390008
      },
      {
        "text": "寻求对话，理解美国真正的诉求。",
        "targetNodeId": 390012
      },
      {
        "text": "联合欧盟，共同向美国施压。",
        "targetNodeId": 390016
      }
    ],
    "createdAt": "2026-01-21T18:06:12.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390007.png",
    "miniGameId": null
  },
  {
    "id": 390008,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 7,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "部长，尼娜，我们不能退缩！格陵兰是丹麦主权不可分割的一部分，我们必须强硬拒绝美国的一切无理要求！",
    "choices": null,
    "createdAt": "2026-01-21T18:06:18.000Z",
    "emotion": "angry",
    "backgroundImage": "assets/backgrounds/scene_390008.png",
    "miniGameId": null,
    "nextNodeId": 390009
  },
  {
    "id": 390009,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 8,
    "nodeType": "dialog",
    "speaker": "拉斯部长",
    "side": "left",
    "avatar": "lars",
    "text": "艾玛……这可能会激化矛盾，让局势变得更糟。但你的决心，我看到了。",
    "choices": null,
    "createdAt": "2026-01-21T18:06:25.000Z",
    "emotion": "sad",
    "backgroundImage": "assets/backgrounds/scene_390009.png",
    "miniGameId": null,
    "nextNodeId": 390010
  },
  {
    "id": 390010,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 9,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "丹麦强硬拒绝美国要求的消息迅速传开。特朗普的推特攻势更加猛烈，国际舆论哗然。我知道，我必须搞清楚华盛顿的真实意图，否则情况会无法收拾。我决定秘密联系迈克尔。",
    "choices": null,
    "createdAt": "2026-01-21T18:06:33.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390010.png",
    "miniGameId": null,
    "nextNodeId": 390011
  },
  {
    "id": 390011,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 10,
    "nodeType": "minigame",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "夜幕降临，我冒着风险秘密潜入美国大使馆，希望能避开警卫和监控，与迈克尔会面。这是一个隐蔽行动，请小心行事。",
    "choices": null,
    "createdAt": "2026-01-21T18:06:40.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390011.png",
    "miniGameId": 150001,
    "nextNodeId": 390012
  },
  {
    "id": 390012,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 11,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "部长，尼娜，也许我们应该先试着和美方对话，了解他们的核心诉求，而不是直接对抗。",
    "choices": null,
    "createdAt": "2026-01-21T18:06:49.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390012.png",
    "miniGameId": null,
    "nextNodeId": 390013
  },
  {
    "id": 390013,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 12,
    "nodeType": "dialog",
    "speaker": "拉斯部长",
    "side": "left",
    "avatar": "lars",
    "text": "艾玛，谨慎是好事。在全面对抗之前，了解对方的底线至关重要。",
    "choices": null,
    "createdAt": "2026-01-21T18:06:56.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390013.png",
    "miniGameId": null,
    "nextNodeId": 390014
  },
  {
    "id": 390014,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 13,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "丹麦向美国发出了对话邀请，虽然初期反应冷淡，但最终他们同意进行非正式接触。我知道，这只是缓兵之计，真正的目的还需要通过迈克尔来探查。我决定秘密联系迈克尔。",
    "choices": null,
    "createdAt": "2026-01-21T18:07:04.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390014.png",
    "miniGameId": null,
    "nextNodeId": 390015
  },
  {
    "id": 390015,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 14,
    "nodeType": "minigame",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "夜幕降临，我冒着风险秘密潜入美国大使馆，希望能避开警卫和监控，与迈克尔会面。这是一个隐蔽行动，请小心行事。",
    "choices": null,
    "createdAt": "2026-01-21T18:07:11.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390015.png",
    "miniGameId": 150002,
    "nextNodeId": 390016
  },
  {
    "id": 390016,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 15,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "部长，尼娜，我认为我们应该寻求欧盟的支持，这会让我们的声音更响亮，也更有分量。",
    "choices": null,
    "createdAt": "2026-01-21T18:07:18.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390016.png",
    "miniGameId": null,
    "nextNodeId": 390017
  },
  {
    "id": 390017,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 16,
    "nodeType": "dialog",
    "speaker": "拉斯部长",
    "side": "left",
    "avatar": "lars",
    "text": "欧盟的支持确实能提供巨大的外交杠杆。这是个明智的选择。",
    "choices": null,
    "createdAt": "2026-01-21T18:07:25.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390017.png",
    "miniGameId": null,
    "nextNodeId": 390018
  },
  {
    "id": 390018,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 17,
    "nodeType": "dialog",
    "speaker": "尼娜",
    "side": "left",
    "avatar": "nina",
    "text": "如果我们能争取到欧盟的支持，美国就不敢轻易妄动了！",
    "choices": null,
    "createdAt": "2026-01-21T18:07:32.000Z",
    "emotion": "happy",
    "backgroundImage": "assets/backgrounds/scene_390018.png",
    "miniGameId": null,
    "nextNodeId": 390019
  },
  {
    "id": 390019,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 18,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "丹麦立即联系欧盟盟友，初步得到了法德两国的口头支持。然而，欧盟内部也存在不同声音，我需要更多华盛顿的内部信息。我决定秘密联系迈克尔。",
    "choices": null,
    "createdAt": "2026-01-21T18:07:39.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390019.png",
    "miniGameId": null,
    "nextNodeId": 390020
  },
  {
    "id": 390020,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 19,
    "nodeType": "minigame",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "夜幕降临，我冒着风险秘密潜入美国大使馆，希望能避开警卫和监控，与迈克尔会面。这是一个隐蔽行动，请小心行事。",
    "choices": null,
    "createdAt": "2026-01-21T18:07:45.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390020.png",
    "miniGameId": 150003,
    "nextNodeId": 390021
  },
  {
    "id": 390021,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 20,
    "nodeType": "dialog",
    "speaker": "迈克尔",
    "side": "left",
    "avatar": "michael",
    "text": "艾玛？你疯了吗？怎么敢亲自来这里！",
    "choices": null,
    "createdAt": "2026-01-21T18:07:51.000Z",
    "emotion": "surprised",
    "backgroundImage": "assets/backgrounds/scene_390021.png",
    "miniGameId": null,
    "nextNodeId": 390022
  },
  {
    "id": 390022,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 21,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "迈克尔，我需要知道，华盛顿的底牌到底是什么？为什么对格陵兰如此执着？",
    "choices": null,
    "createdAt": "2026-01-21T18:08:00.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390022.png",
    "miniGameId": null,
    "nextNodeId": 390023
  },
  {
    "id": 390023,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 22,
    "nodeType": "dialog",
    "speaker": "迈克尔",
    "side": "left",
    "avatar": "michael",
    "text": "他们真正想要的是格陵兰的稀土矿产。那里的储量惊人，足以改变全球的能源格局……",
    "choices": null,
    "createdAt": "2026-01-21T18:08:06.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390023.png",
    "miniGameId": null,
    "nextNodeId": 390024
  },
  {
    "id": 390024,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 23,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "（Minigame Failure Path）行动被察觉，虽然仍获得部分信息，但美方对我的举动保持警惕。迈克尔冒险透露了稀土矿产的秘密，但同时也警告我，现在我们的一举一动都被严密监控。",
    "choices": null,
    "createdAt": "2026-01-21T18:08:13.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390024.png",
    "miniGameId": null,
    "nextNodeId": 390025
  },
  {
    "id": 390025,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 24,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "迈克尔透露的稀土矿产信息震惊了我。与此同时，特朗普再次发推嘲讽丹麦军队只有“两个狗拉雪橇”，丹麦舆论彻底炸锅。街头的抗议规模不断扩大。",
    "choices": null,
    "createdAt": "2026-01-21T18:08:22.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390025.png",
    "miniGameId": null,
    "nextNodeId": 390026
  },
  {
    "id": 390026,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 25,
    "nodeType": "minigame",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "数万民众涌上街头，愤怒的情绪一触即发。首相要求我作为外交官代表政府发表演讲，安抚民众情绪，同时传递丹麦坚决维护主权的决心。请把握节奏，鼓舞人心！",
    "choices": null,
    "createdAt": "2026-01-21T18:08:28.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390026.png",
    "miniGameId": 150004,
    "nextNodeId": 390027
  },
  {
    "id": 390027,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 26,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "我的演讲句句有力，充满民族自豪感，成功安抚了愤怒的民众。他们开始相信政府能够妥善处理危机，为丹麦赢得了宝贵的喘息时间。",
    "choices": null,
    "createdAt": "2026-01-21T18:08:37.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390027.png",
    "miniGameId": null,
    "nextNodeId": 390028
  },
  {
    "id": 390028,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 27,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "（Minigame Failure Path）我的演讲未能完全平息民众的怒火，反而因为一些不当的措辞激化了部分情绪。舆论开始两极分化，政府承受更大压力。",
    "choices": null,
    "createdAt": "2026-01-21T18:08:45.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390028.png",
    "miniGameId": null,
    "nextNodeId": 390029
  },
  {
    "id": 390029,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 28,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "不久，美国宣布对丹麦征收10%的关税。丹麦经济界开始施压政府，要求尽快妥协，避免更大的经济损失。",
    "choices": null,
    "createdAt": "2026-01-21T18:08:51.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390029.png",
    "miniGameId": null,
    "nextNodeId": 390030
  },
  {
    "id": 390030,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 29,
    "nodeType": "dialog",
    "speaker": "尼娜",
    "side": "left",
    "avatar": "nina",
    "text": "艾玛，我有一个大胆的想法。格陵兰独立！不属于丹麦，也不属于美国。成为一个中立国！",
    "choices": null,
    "createdAt": "2026-01-21T18:08:52.000Z",
    "emotion": "surprised",
    "backgroundImage": "assets/backgrounds/scene_390030.png",
    "miniGameId": null,
    "nextNodeId": 390031
  },
  {
    "id": 390031,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 30,
    "nodeType": "dialog",
    "speaker": "迈克尔",
    "side": "left",
    "avatar": "michael",
    "text": "华盛顿的消息，特朗普的支持率因为格陵兰事件正在下降，美国军方也普遍反对这个计划，担心它会损害北约的团结。",
    "choices": null,
    "createdAt": "2026-01-21T18:09:00.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390031.png",
    "miniGameId": null,
    "nextNodeId": 390032
  },
  {
    "id": 390032,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 31,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "北约紧急会议召开，各国态度不一。一些盟友担心与美国撕破脸，另一些则支持丹麦的主权。我必须再次做出关键选择。",
    "choices": null,
    "createdAt": "2026-01-21T18:09:08.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390032.png",
    "miniGameId": null,
    "nextNodeId": 390033
  },
  {
    "id": 390033,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 32,
    "nodeType": "choice",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "在北约会议上，你将如何发言？",
    "choices": [
      {
        "text": "呼吁北约盟友集体防御，共同对抗美国的威胁。",
        "targetNodeId": 390034
      },
      {
        "text": "寻求双边解决，避免北约内部的分裂。",
        "targetNodeId": 390037
      },
      {
        "text": "考虑妥协方案，寻求各方都能接受的中间路线。",
        "targetNodeId": 390040
      }
    ],
    "createdAt": "2026-01-21T18:09:15.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390033.png",
    "miniGameId": null
  },
  {
    "id": 390034,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 33,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "北约存在的意义就是捍卫成员国的安全与主权！我们现在需要的是集体的力量，而不是各自为政！",
    "choices": null,
    "createdAt": "2026-01-21T18:09:21.000Z",
    "emotion": "angry",
    "backgroundImage": "assets/backgrounds/scene_390034.png",
    "miniGameId": null,
    "nextNodeId": 390035
  },
  {
    "id": 390035,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 34,
    "nodeType": "dialog",
    "speaker": "拉斯部长",
    "side": "left",
    "avatar": "lars",
    "text": "这会考验北约的团结，但也是我们作为盟友应尽的职责。",
    "choices": null,
    "createdAt": "2026-01-21T18:09:29.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390035.png",
    "miniGameId": null,
    "nextNodeId": 390036
  },
  {
    "id": 390036,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 35,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "丹麦在北约会议上坚定地呼吁集体防御，得到了部分成员国的积极响应，但也加剧了北约内部对于是否要与美国公开对抗的分歧。接下来，欧盟峰会即将召开。",
    "choices": null,
    "createdAt": "2026-01-21T18:09:37.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390036.png",
    "miniGameId": null,
    "nextNodeId": 390037
  },
  {
    "id": 390037,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 36,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "在北约内部寻求共识可能更困难。也许我们应该将重点放在与美国的双边对话上，寻求一个直接的解决方案。",
    "choices": null,
    "createdAt": "2026-01-21T18:09:38.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390037.png",
    "miniGameId": null,
    "nextNodeId": 390038
  },
  {
    "id": 390038,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 37,
    "nodeType": "dialog",
    "speaker": "拉斯部长",
    "side": "left",
    "avatar": "lars",
    "text": "双边谈判需要高超的技巧，而且风险很高。但如果能避免北约分裂，或许值得一试。",
    "choices": null,
    "createdAt": "2026-01-21T18:09:47.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390038.png",
    "miniGameId": null,
    "nextNodeId": 390039
  },
  {
    "id": 390039,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 38,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "丹麦方面开始秘密与美国进行双边接触。美国态度有所软化，但依然坚持其核心诉求。所有人的目光都转向了即将召开的欧盟峰会。",
    "choices": null,
    "createdAt": "2026-01-21T18:09:54.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390039.png",
    "miniGameId": null,
    "nextNodeId": 390040
  },
  {
    "id": 390040,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 39,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "迈克尔的情報和经济界的压力让我意识到，也许我们真的需要一个妥协方案，一个各方都能接受的中间路线。",
    "choices": null,
    "createdAt": "2026-01-21T18:10:00.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390040.png",
    "miniGameId": null,
    "nextNodeId": 390041
  },
  {
    "id": 390041,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 40,
    "nodeType": "dialog",
    "speaker": "尼娜",
    "side": "left",
    "avatar": "nina",
    "text": "妥协？艾玛，这等于出卖格陵兰的未来！我们不能这样做！",
    "choices": null,
    "createdAt": "2026-01-21T18:10:08.000Z",
    "emotion": "angry",
    "backgroundImage": "assets/backgrounds/scene_390041.png",
    "miniGameId": null,
    "nextNodeId": 390042
  },
  {
    "id": 390042,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 41,
    "nodeType": "dialog",
    "speaker": "拉斯部长",
    "side": "left",
    "avatar": "lars",
    "text": "艾玛，外交的艺术有时就是要在糟糕的选项中，选择那个最不坏的。但这个度，很难把握。",
    "choices": null,
    "createdAt": "2026-01-21T18:10:17.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390042.png",
    "miniGameId": null,
    "nextNodeId": 390043
  },
  {
    "id": 390043,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 42,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "丹麦政府内部开始讨论各种妥协方案，这引起了格陵兰代表的强烈不满，但也得到了一些国际观察员的认同。欧盟峰会迫在眉睫，我必须做出最终的决定。",
    "choices": null,
    "createdAt": "2026-01-21T18:10:24.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390043.png",
    "miniGameId": null,
    "nextNodeId": 390044
  },
  {
    "id": 390044,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 43,
    "nodeType": "choice",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "在欧盟峰会上，你将提出什么方案？",
    "choices": [
      {
        "text": "坚持主权不可谈判，呼吁欧盟集体声援。",
        "targetNodeId": 390044
      },
      {
        "text": "提出格陵兰稀土资源开发合作方案，邀请多方参与。",
        "targetNodeId": 390054
      },
      {
        "text": "支持格陵兰独立，成为一个中立国。",
        "targetNodeId": null
      }
    ],
    "createdAt": "2026-01-21T18:10:32.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390044.png",
    "miniGameId": null
  },
  {
    "id": 390045,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 44,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "尊敬的各位领导人，格陵兰是丹麦主权的一部分，这是不可谈判的底线！我们请求欧盟盟友，团结起来，共同捍卫国际法和成员国的主权完整！",
    "choices": null,
    "createdAt": "2026-01-21T18:10:39.000Z",
    "emotion": "angry",
    "backgroundImage": "assets/backgrounds/scene_390045.png",
    "miniGameId": null,
    "nextNodeId": 390046
  },
  {
    "id": 390046,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 45,
    "nodeType": "dialog",
    "speaker": "欧盟领导人",
    "side": "left",
    "avatar": "eu_leader",
    "text": "我们理解丹麦的立场。法德两国将明确表示对丹麦主权的坚定支持，但同时，我们也要避免局势失控。",
    "choices": null,
    "createdAt": "2026-01-21T18:10:46.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390046.png",
    "miniGameId": null,
    "nextNodeId": 390047
  },
  {
    "id": 390047,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 46,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "欧盟峰会上，丹麦的强硬立场得到了法德领导人的公开支持。特朗普闻讯大怒，威胁要对整个欧盟加征关税，全球贸易战的阴影笼罩而来。我深知接下来记者会的重要性。",
    "choices": null,
    "createdAt": "2026-01-21T18:10:52.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390047.png",
    "miniGameId": null,
    "nextNodeId": 390048
  },
  {
    "id": 390048,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 47,
    "nodeType": "minigame",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "记者会上，闪光灯此起彼伏，来自世界各地的记者抛出尖锐问题。你必须保持冷静，策略性地回答问题，巩固丹麦的国际形象，并避免激化矛盾。请选择最佳的回答策略！",
    "choices": null,
    "createdAt": "2026-01-21T18:10:58.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390048.png",
    "miniGameId": 150005,
    "nextNodeId": 390049
  },
  {
    "id": 390049,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 48,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "（Minigame Success）我的回答滴水不漏，逻辑清晰，成功为丹麦赢得了国际社会的同情与支持。舆论开始转向，华盛顿传来消息：特朗普将亲自致电丹麦首相，希望寻求对话。",
    "choices": null,
    "createdAt": "2026-01-21T18:11:06.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390049.png",
    "miniGameId": null,
    "nextNodeId": 390050
  },
  {
    "id": 390050,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 49,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "我被选中参与了与特朗普的电话会议。格陵兰议会随后投票，尼娜发表了激情的演讲，强调格陵兰人民的自决权。欧盟宣布了对美国的反制措施，北约内部的分裂愈发明显。",
    "choices": null,
    "createdAt": "2026-01-21T18:11:14.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390050.png",
    "miniGameId": null,
    "nextNodeId": 390051
  },
  {
    "id": 390051,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 50,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "【结局】坚持原则：国际社会的强大压力最终迫使特朗普放弃了吞并格陵兰的计划。丹麦捍卫了国家主权和国际法尊严，但美丹关系跌至冰点，信任严重受损。虽然格陵兰仍属丹麦，但代价巨大，未来的国际格局因此改变。",
    "choices": null,
    "createdAt": "2026-01-21T18:11:25.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390051.png",
    "miniGameId": null,
    "nextNodeId": 390052
  },
  {
    "id": 390052,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 51,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "（Minigame Failure）我的回答稍显犹豫，被媒体抓住把柄，局势对丹麦不利。华盛顿态度变得更加强硬，拒绝了所有对话渠道，并加大了经济制裁力度。世界局势变得更加紧张。",
    "choices": null,
    "createdAt": "2026-01-21T18:11:31.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390052.png",
    "miniGameId": null,
    "nextNodeId": 390053
  },
  {
    "id": 390053,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 52,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "【结局】激进对抗：外交完全破裂，美国对丹麦实施全面制裁，北约内部因为格陵兰危机而陷入彻底分裂。世界局势急剧恶化，新冷战的阴影笼罩全球，小国在国际舞台上的生存空间变得岌岌可危。",
    "choices": null,
    "createdAt": "2026-01-21T18:11:38.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390053.png",
    "miniGameId": null,
    "nextNodeId": 390054
  },
  {
    "id": 390054,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 53,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "与其僵持不下，不如将格陵兰的稀土资源作为一个谈判筹码。我提议，由丹麦主导，建立一个国际合作开发框架，确保资源共享与可持续发展，邀请美国和欧盟共同参与。",
    "choices": null,
    "createdAt": "2026-01-21T18:11:48.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390054.png",
    "miniGameId": null,
    "nextNodeId": 390055
  },
  {
    "id": 390055,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 54,
    "nodeType": "dialog",
    "speaker": "欧盟领导人",
    "side": "left",
    "avatar": "eu_leader",
    "text": "这是一个具有创造性的方案。在尊重丹麦主权的前提下，它为各方提供了一个解决争端的可能性。我们表示支持。",
    "choices": null,
    "createdAt": "2026-01-21T18:11:56.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390055.png",
    "miniGameId": null,
    "nextNodeId": 390056
  },
  {
    "id": 390056,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 55,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "丹麦提出的资源合作方案得到了欧盟的初步支持。美国内部对此也有讨论，但仍未明确表态。我深知接下来记者会的重要性。",
    "choices": null,
    "createdAt": "2026-01-21T18:12:06.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390056.png",
    "miniGameId": null,
    "nextNodeId": 390057
  },
  {
    "id": 390057,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 56,
    "nodeType": "minigame",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "记者会上，闪光灯此起彼伏，来自世界各地的记者抛出尖锐问题。你必须保持冷静，策略性地回答问题，巩固丹麦的国际形象，并避免激化矛盾。请选择最佳的回答策略！",
    "choices": null,
    "createdAt": "2026-01-21T18:12:14.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390057.png",
    "miniGameId": 150006,
    "nextNodeId": 390058
  },
  {
    "id": 390058,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 57,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "（Minigame Success）我的回答为合作方案赢得了国际社会的广泛认可。丹麦展现了灵活与智慧，成功缓和了紧张局势。华盛顿传来消息：特朗普将亲自致电丹麦首相，希望就此方案进行进一步谈判。",
    "choices": null,
    "createdAt": "2026-01-21T18:12:24.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390058.png",
    "miniGameId": null,
    "nextNodeId": 390059
  },
  {
    "id": 390059,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 58,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "我被选中参与了与特朗普的电话会议。格陵兰议会投票，尼娜发表了激情的演讲，强调格陵兰人民的未来由他们自己决定。在多方拉锯下，最终各方达成了协议。",
    "choices": null,
    "createdAt": "2026-01-21T18:12:30.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390059.png",
    "miniGameId": null,
    "nextNodeId": 390060
  },
  {
    "id": 390060,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 59,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "【结局】选择妥协：经过漫长而艰难的谈判，丹麦与美国达成协议：美国获得格陵兰部分军事基地的长期使用权，以确保北极安全；格陵兰获得更大的自治权和稀土资源开发的主导权，但收益与丹麦和美国分享。各方都不完全满意，但也都接受了这个“最不坏”的结局。",
    "choices": null,
    "createdAt": "2026-01-21T18:12:39.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390060.png",
    "miniGameId": null,
    "nextNodeId": 390061
  },
  {
    "id": 390061,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 60,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "（Minigame Failure）我的回答未能消除疑虑，方案面临巨大的阻力，国际社会对合作前景充满悲观。华盛顿对丹麦的方案持观望态度，并继续施加经济压力。",
    "choices": null,
    "createdAt": "2026-01-21T18:12:47.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390061.png",
    "miniGameId": null,
    "nextNodeId": 390062
  },
  {
    "id": 390062,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 61,
    "nodeType": "narrator",
    "speaker": null,
    "side": null,
    "avatar": null,
    "text": "【结局】激进对抗：外交完全破裂，美国对丹麦实施全面制裁，北约内部因为格陵兰危机而陷入彻底分裂。世界局势急剧恶化，新冷战的阴影笼罩全球，小国在国际舞台上的生存空间变得岌岌可危。",
    "choices": null,
    "createdAt": "2026-01-21T18:12:59.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390062.png",
    "miniGameId": null,
    "nextNodeId": 390063
  },
  {
    "id": 390063,
    "gameId": 420002,
    "characterId": "emma",
    "nodeIndex": 62,
    "nodeType": "dialog",
    "speaker": "emma",
    "side": "right",
    "avatar": "emma",
    "text": "鉴于格陵兰人民的强烈意愿和特殊的地理位置，我们或许可以探索支持格陵兰独立，使其成为一个在国际社会监督下的中立国。这也许能一劳永逸地解决争端。",
    "choices": null,
    "createdAt": "2026-01-21T18:13:06.000Z",
    "emotion": "neutral",
    "backgroundImage": "assets/backgrounds/scene_390063.png",
    "miniGameId": null
  }
];

const CHARACTERS = [
  {
    "id": 420005,
    "gameId": 420002,
    "characterId": "emma",
    "name": "艾玛·安德森",
    "description": "年轻丹麦外交官，力挽狂澜处理危机。",
    "isProtagonist": 1,
    "createdAt": "2026-01-21T18:02:43.000Z",
    "spriteNeutral": "assets/characters/Emma_Neutral.png",
    "spriteHappy": "assets/characters/Emma_Happy.png",
    "spriteSad": "assets/characters/Emma_Sad.png",
    "spriteAngry": "assets/characters/Emma_Angry.png",
    "spriteSurprised": "assets/characters/Emma_Surprised.png"
  },
  {
    "id": 420006,
    "gameId": 420002,
    "characterId": "lars",
    "name": "拉斯部长",
    "description": "艾玛的导师，主张拖延化解危机。",
    "isProtagonist": 0,
    "createdAt": "2026-01-21T18:03:14.000Z",
    "spriteNeutral": "assets/characters/Lars_Neutral.png",
    "spriteHappy": "assets/characters/Lars_Happy.png",
    "spriteSad": "assets/characters/Lars_Sad.png",
    "spriteAngry": "assets/characters/Lars_Angry.png",
    "spriteSurprised": "assets/characters/Lars_Surprised.png"
  },
  {
    "id": 420007,
    "gameId": 420002,
    "characterId": "nina",
    "name": "尼娜",
    "description": "格陵兰代表，为格陵兰独立而奔走。",
    "isProtagonist": 0,
    "createdAt": "2026-01-21T18:03:49.000Z",
    "spriteNeutral": "assets/characters/Nina_Neutral.png",
    "spriteHappy": "assets/characters/Nina_Happy.png",
    "spriteSad": "assets/characters/Nina_Sad.png",
    "spriteAngry": "assets/characters/Nina_Angry.png",
    "spriteSurprised": "assets/characters/Nina_Surprised.png"
  },
  {
    "id": 420008,
    "gameId": 420002,
    "characterId": "michael",
    "name": "迈克尔",
    "description": "艾玛的美国朋友，提供内部情报。",
    "isProtagonist": 0,
    "createdAt": "2026-01-21T18:04:22.000Z",
    "spriteNeutral": "assets/characters/Michael_Neutral.png",
    "spriteHappy": "assets/characters/Michael_Happy.png",
    "spriteSad": "assets/characters/Michael_Sad.png",
    "spriteAngry": "assets/characters/Michael_Angry.png",
    "spriteSurprised": "assets/characters/Michael_Surprised.png"
  }
];

const MINIGAMES = [
  {
    "id": 150001,
    "gameId": 420002,
    "gameType": "stealth",
    "title": "夜幕降临，我冒着风险秘密潜入美国大使馆，希望能避开警卫和监控，与迈克尔会面。这是一个隐蔽行动，请小心行事。",
    "description": "夜幕降临，我冒着风险秘密潜入美国大使馆，希望能避开警卫和监控，与迈克尔会面。这是一个隐蔽行动，请小心行事。",
    "config": null,
    "successNextIndex": 19,
    "failureNextIndex": 22,
    "createdAt": "2026-01-21T18:06:40.000Z"
  },
  {
    "id": 150002,
    "gameId": 420002,
    "gameType": "stealth",
    "title": "夜幕降临，我冒着风险秘密潜入美国大使馆，希望能避开警卫和监控，与迈克尔会面。这是一个隐蔽行动，请小心行事。",
    "description": "夜幕降临，我冒着风险秘密潜入美国大使馆，希望能避开警卫和监控，与迈克尔会面。这是一个隐蔽行动，请小心行事。",
    "config": null,
    "successNextIndex": 19,
    "failureNextIndex": 22,
    "createdAt": "2026-01-21T18:07:11.000Z"
  },
  {
    "id": 150003,
    "gameId": 420002,
    "gameType": "stealth",
    "title": "夜幕降临，我冒着风险秘密潜入美国大使馆，希望能避开警卫和监控，与迈克尔会面。这是一个隐蔽行动，请小心行事。",
    "description": "夜幕降临，我冒着风险秘密潜入美国大使馆，希望能避开警卫和监控，与迈克尔会面。这是一个隐蔽行动，请小心行事。",
    "config": null,
    "successNextIndex": 19,
    "failureNextIndex": 22,
    "createdAt": "2026-01-21T18:07:45.000Z"
  },
  {
    "id": 150004,
    "gameId": 420002,
    "gameType": "rhythm",
    "title": "数万民众涌上街头，愤怒的情绪一触即发。首相要求我作为外交官代表政府发表演讲，安抚民众情绪，同时传递丹麦坚决维护主权的决心。请把握节奏，鼓舞人心！",
    "description": "数万民众涌上街头，愤怒的情绪一触即发。首相要求我作为外交官代表政府发表演讲，安抚民众情绪，同时传递丹麦坚决维护主权的决心。请把握节奏，鼓舞人心！",
    "config": null,
    "successNextIndex": 26,
    "failureNextIndex": 27,
    "createdAt": "2026-01-21T18:08:28.000Z"
  },
  {
    "id": 150005,
    "gameId": 420002,
    "gameType": "strategy",
    "title": "记者会上，闪光灯此起彼伏，来自世界各地的记者抛出尖锐问题。你必须保持冷静，策略性地回答问题，巩固丹麦的国际形象，并避免激化矛盾。请选择最佳的回答策略！",
    "description": "记者会上，闪光灯此起彼伏，来自世界各地的记者抛出尖锐问题。你必须保持冷静，策略性地回答问题，巩固丹麦的国际形象，并避免激化矛盾。请选择最佳的回答策略！",
    "config": null,
    "successNextIndex": 47,
    "failureNextIndex": 50,
    "createdAt": "2026-01-21T18:10:58.000Z"
  },
  {
    "id": 150006,
    "gameId": 420002,
    "gameType": "strategy",
    "title": "记者会上，闪光灯此起彼伏，来自世界各地的记者抛出尖锐问题。你必须保持冷静，策略性地回答问题，巩固丹麦的国际形象，并避免激化矛盾。请选择最佳的回答策略！",
    "description": "记者会上，闪光灯此起彼伏，来自世界各地的记者抛出尖锐问题。你必须保持冷静，策略性地回答问题，巩固丹麦的国际形象，并避免激化矛盾。请选择最佳的回答策略！",
    "config": null,
    "successNextIndex": 57,
    "failureNextIndex": 60,
    "createdAt": "2026-01-21T18:12:14.000Z"
  }
];
